# Generated by Django 5.2.6 on 2025-09-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cartitem_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='minimum_cart_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
