# Generated by Django 5.2.6 on 2025-09-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_order_product_name_order_status_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniturecategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
